- name: install and run nginx
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: Start a service
    ansible.builtin.service:
      name: nginx
      state: started     
