- name: variables
  hosts: local
  connection: local
  vars:
    COURSE: "DEVOPS WITH AWS"
    DURATION: 120HRS
    TRAINER: JAYANTHI
  tasks:
  - name: print the variable
    ansible.builtin.debug:
      msg: "Couser is {{COURSE}},Duration is {{DURATION}}, Trainer is {{TRAINER}}"
  
