- name: variables
  hosts: local
  connection: local
  tasks:
  - name: print the variable
    ansible.builtin.debug:
      msg: "Couser is devops with AWS,Duration is 120hrs, Trainer is jayanthi"
  
