- name: variables
  hosts: local
  connection: local
  vars: #global variables
    COURSE: "DevOps with AWS"
    DURATION: 120HRS
    TRAINER: Jayanthi
  tasks: 
  - name: Local variable1
    vars: #Local variables
      COURSE: "ANSIBLE"
    ansible.builtin.debug:
      msg: "Course is {{COURSE}}, Duration is {{DURATION}}, Trainer is {{TRAINER}}"
  
  - name:  print Global variables
    ansible.builtin.debug:
      msg: "Course is {{COURSE}}, Duration is {{DURATION}}, Trainer is {{TRAINER}}"
