- name: install Nginx
  hosts: web
  become: yes
  tasks:
  - name: Installing nginx in RedHat
    ansible.builtin.dnf:
      state : installed
      enabled: yes
    when: ansible_os_family == 'RedHat' 
 
  - name: Installing Ubantu in Debian
    ansible.builtin.apt:
      state : installed
      enabled: yes
    when: ansible_os_family == 'Debian'       
