- name: install Nginx
  hosts: web
  become: yes
  tasks:
  - name: Installing nginx in RedHat
    ansible.builtin.package
      status : started
      enabled: yes
    when: {{ ansible_os_family == 'RedHat' }} 
 
  - name: Installing Ubantu in Debian
    ansible.builtin.apt
      status : started
      enabled: yes
  when: {{ ansible_os_family == 'Debian' }}       
