- name: loops
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.debug:
      msg: "{{ item }}"
    loop:
    - linux
    - shellscript
    - ansible
    - terraform

