- name: handling undefined variable
  hosts: web
  tasks:

  - name: undefined variable handling
    ansible.builtin.debug:
      msg: "{{ person | default('Jayanthi') }}"

  - name: string to list
    vars:
      fruits: apple,banana,orange
    ansible.builtin.debug:
      msg: "{{ fruits | split(',') }}"

  - name: map to list
    vars:
      course:
        name: ansible
        duration: 120 hrs
        trainer: jayanthi
    ansible.builtin.debug:
      msg: "{{ course | dict2items }}" 

  - name: list to map
    vars:
     course:  [
        {
            "key": "name",
            "value": "ansible"
        },
        {
            "key": "duration",
            "value": "120 hrs"
        },
        {
            "key": "trainer",
            "value": "jayanthi"
        }
    ]
    ansible.builtin.debug:
      msg: "{{ course | items2dict }}"

  - name: upper to lowercase
    vars:
      name: "JAYAnthi"
    ansible.builtin.debug:
      msg: "{{ name | lower }}"

  - name: lower to upper
    vars:
      name: "jayanthi"
    ansible.builtin.debug:
      msg: "{{ name | upper }}" 

  - name: min and max number
    vars:
      number : "1,2,5,9"
    ansible.builtin.debug:
      msg: " MIN : {{ number | min }} , MAX : {{ number | max }} "                 

           



