- name: handling undefined variable
  hosts: web
  tasks:
  - name: undefined variable handling
    ansible.builtin.debug:
      msg: "{{ person | default('Jayanthi') }}"

  - name: string to list
    vars:
      fruits: apple,banana,orange
    ansible.builtin.debug:
      msg: "{{ fruits | split(',') }}"

  - name: map to list
    vars:
      course:
        name: ansible
        duration: 120 hrs
        trainer: jayanthi
    ansible.builtin.debug:
      msg: "{{ course | dict2items }}"        



